services:
  tarantool-kv:
    image: tarantool/tarantool:3.2.0
    container_name: tarantool-kv
    ports:
      - "3301:3301"
    volumes:
      - ./init.lua:/opt/tarantool/init.lua
    command: tarantool /opt/tarantool/init.lua